sylius_twig_hooks:
    hooks:
        'sylius_shop.account.login.content.login_container':
            google_login:
                template: 'shop/google_login_button.html.twig'
                priority: -100

        'sylius_shop.account.register.content':
            google_login:
                template: 'shop/google_login_button.html.twig'
                priority: -100
