sylius_mailer:
    emails:
        admin_order_placed:
            subject: oma.email.admin_order_placed.subject
            template: 'email/adminOrderPlaced.html.twig'
        admin_customer_registered:
            subject: oma.email.admin_customer_registered.subject
            template: 'email/adminCustomerRegistered.html.twig'
        admin_product_review_created:
            subject: oma.email.admin_product_review_created.subject
            template: 'email/adminProductReviewCreated.html.twig'
        admin_product_out_of_stock:
            subject: oma.email.admin_product_out_of_stock.subject
            template: 'email/adminProductOutOfStock.html.twig'
