parameters:
    env(TRUSTED_PROXIES): ''

framework:
    session:
        save_path: '%kernel.project_dir%/var/sessions'
    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-proto', 'x-forwarded-port']
